In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pwd

'C:\\Users\\Fulvio'

In [3]:
df = pd.read_excel('DATA_BASE AKI e NON AKI_FINAL VERSION (1).xlsx', sheet_name='Sheet1')

In [4]:
df

,DATA INTERVENTO,Codice identificativo,BSA,SMOKING (0: NO; 1: EX-SMOKER; 2: SMOKER),POOR MOBILITY 0/1 (severe impairment of mobility secondary to musculoskeletal or neurological dysfunction),DIABETES MELLITUS 0/1,INSULINE 0/1,ANGINE AT REST 0/1,ATRIAL FIBRILLATION 0/1,COPD 0/1,...,AKI persistent(non_corretto)\n ≥ 7d after surg.I: \n≥ 1.5 or ≥ + 0.3 (or after AKI incidence),AKI incomplete recovery (non_corretto)\n(d after surg): down 1 stage; for stage 1 \nCr. peak ¯ by ≥20% and/or no AKI or CR (or after AKI incidence),IR after AKI(non_corretto),AKI complete recovery after surg:(non_corretto)\nCr increase\n ≤ 0.15mg/dl or X 1.25 (or after AKI incidence),CR after AKI,ESORDIO,FU,Unnamed: 170,Durata azzurra,Unnamed: 172
0,3.03,SaEl0002,1.62,0,0,0,0,0,1.0,0,...,NO,NO,NaN,4d,3d,NaN,NaN,1a,NaN,NaN
1,2.03,VeAl0003,1.98,0,0,1,0,0,1.0,0,...,NO,4d (da 2 a 1),4d,6d,6d,NaN,NaN,NaN,NaN,NaN
2,1.03,BoVi0004,1.45,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.03,GiAn0005,1.55,0,0,0,0,1,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60.00,StAu0006,1.74,1,0,0,0,0,0.0,0,...,16d,4d (da 3 a 2; da 2 a 1 6d poi 9d),4d,NO,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,43453.00,GiCa1122,1.5,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1061,43454.00,MaLu1123,1.9,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,43454.00,CoCl1124,2.1,0,0,1,1,0,0.0,1,...,10d,6d (da 3 a 2; da 2 a 1 8d),6d,NO,NaN,NaN,NaN,NaN,NaN,NaN
1063,43453.00,LoGi1125,1.96,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064,43455.00,PaDe1126,1.81,0,0,1,1,0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df['New MI 0/1'].isna().sum()

5

In [9]:
df[['REOPERATION (for bleeding)  0/1', 'New MI 0/1','New Strokes 0/1', 'Infections (sternal wound infection or cest infection or septicemia) 0/1', 'No wound healing 0/1', 'New HF 0/1', 'Cardiac arrest 0/1']] = df[['REOPERATION (for bleeding)  0/1', 'New MI 0/1','New Strokes 0/1', 'Infections (sternal wound infection or cest infection or septicemia) 0/1', 'No wound healing 0/1', 'New HF 0/1', 'Cardiac arrest 0/1']].fillna('-')

In [11]:
df['ICU stay (days)'] = df['ICU stay (days)'].fillna('-')

In [12]:
df

,DATA INTERVENTO,Codice identificativo,BSA,SMOKING (0: NO; 1: EX-SMOKER; 2: SMOKER),POOR MOBILITY 0/1 (severe impairment of mobility secondary to musculoskeletal or neurological dysfunction),DIABETES MELLITUS 0/1,INSULINE 0/1,ANGINE AT REST 0/1,ATRIAL FIBRILLATION 0/1,COPD 0/1,...,AKI persistent(non_corretto)\n ≥ 7d after surg.I: \n≥ 1.5 or ≥ + 0.3 (or after AKI incidence),AKI incomplete recovery (non_corretto)\n(d after surg): down 1 stage; for stage 1 \nCr. peak ¯ by ≥20% and/or no AKI or CR (or after AKI incidence),IR after AKI(non_corretto),AKI complete recovery after surg:(non_corretto)\nCr increase\n ≤ 0.15mg/dl or X 1.25 (or after AKI incidence),CR after AKI,ESORDIO,FU,Unnamed: 170,Durata azzurra,Unnamed: 172
0,3.03,SaEl0002,1.62,0,0,0,0,0,1.0,0,...,NO,NO,NaN,4d,3d,NaN,NaN,1a,NaN,NaN
1,2.03,VeAl0003,1.98,0,0,1,0,0,1.0,0,...,NO,4d (da 2 a 1),4d,6d,6d,NaN,NaN,NaN,NaN,NaN
2,1.03,BoVi0004,1.45,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.03,GiAn0005,1.55,0,0,0,0,1,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60.00,StAu0006,1.74,1,0,0,0,0,0.0,0,...,16d,4d (da 3 a 2; da 2 a 1 6d poi 9d),4d,NO,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,43453.00,GiCa1122,1.5,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1061,43454.00,MaLu1123,1.9,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,43454.00,CoCl1124,2.1,0,0,1,1,0,0.0,1,...,10d,6d (da 3 a 2; da 2 a 1 8d),6d,NO,NaN,NaN,NaN,NaN,NaN,NaN
1063,43453.00,LoGi1125,1.96,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064,43455.00,PaDe1126,1.81,0,0,1,1,0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df['ICU stay (days)']

0       6
1       4
2       3
3       2
4       8
       ..
1060    3
1061    2
1062    7
1063    2
1064    3
Name: ICU stay (days), Length: 1065, dtype: object

In [26]:
df

,DATA INTERVENTO,Codice identificativo,BSA,SMOKING (0: NO; 1: EX-SMOKER; 2: SMOKER),POOR MOBILITY 0/1 (severe impairment of mobility secondary to musculoskeletal or neurological dysfunction),DIABETES MELLITUS 0/1,INSULINE 0/1,ANGINE AT REST 0/1,ATRIAL FIBRILLATION 0/1,COPD 0/1,...,AKI persistent(non_corretto)\n ≥ 7d after surg.I: \n≥ 1.5 or ≥ + 0.3 (or after AKI incidence),AKI incomplete recovery (non_corretto)\n(d after surg): down 1 stage; for stage 1 \nCr. peak ¯ by ≥20% and/or no AKI or CR (or after AKI incidence),IR after AKI(non_corretto),AKI complete recovery after surg:(non_corretto)\nCr increase\n ≤ 0.15mg/dl or X 1.25 (or after AKI incidence),CR after AKI,ESORDIO,FU,Unnamed: 170,Durata azzurra,Unnamed: 172
0,3.03,SaEl0002,1.62,0,0,0,0,0,1.0,0,...,NO,NO,NaN,4d,3d,NaN,NaN,1a,NaN,NaN
1,2.03,VeAl0003,1.98,0,0,1,0,0,1.0,0,...,NO,4d (da 2 a 1),4d,6d,6d,NaN,NaN,NaN,NaN,NaN
2,1.03,BoVi0004,1.45,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.03,GiAn0005,1.55,0,0,0,0,1,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60.00,StAu0006,1.74,1,0,0,0,0,0.0,0,...,16d,4d (da 3 a 2; da 2 a 1 6d poi 9d),4d,NO,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,43453.00,GiCa1122,1.5,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1061,43454.00,MaLu1123,1.9,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,43454.00,CoCl1124,2.1,0,0,1,1,0,0.0,1,...,10d,6d (da 3 a 2; da 2 a 1 8d),6d,NO,NaN,NaN,NaN,NaN,NaN,NaN
1063,43453.00,LoGi1125,1.96,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064,43455.00,PaDe1126,1.81,0,0,1,1,0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df_1 = df[['REOPERATION (for bleeding)  0/1', 'New MI 0/1','New Strokes 0/1', 'Infections (sternal wound infection or cest infection or septicemia) 0/1', 'No wound healing 0/1', 'New HF 0/1', 'Cardiac arrest 0/1', 'ICU stay (days)']]

In [28]:
df_1

,REOPERATION (for bleeding) 0/1,New MI 0/1,New Strokes 0/1,Infections (sternal wound infection or cest infection or septicemia) 0/1,No wound healing 0/1,New HF 0/1,Cardiac arrest 0/1,ICU stay (days)
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,8
...,...,...,...,...,...,...,...,...
1060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
1061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
1063,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1064,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3

In [29]:
df_1 = df[['REOPERATION (for bleeding)  0/1', 'New MI 0/1','New Strokes 0/1', 'Infections (sternal wound infection or cest infection or septicemia) 0/1', 'No wound healing 0/1', 'New HF 0/1', 'Cardiac arrest 0/1', 'ICU stay (days)', 'SEX', 'AGE years']]

In [30]:
df_1

,REOPERATION (for bleeding) 0/1,New MI 0/1,New Strokes 0/1,Infections (sternal wound infection or cest infection or septicemia) 0/1,No wound healing 0/1,New HF 0/1,Cardiac arrest 0/1,ICU stay (days),SEX,AGE years
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6,F,74
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4,M,69
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3,F,75
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,F,62
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,8,M,66
...,...,...,...,...,...,...,...,...,...,...
1060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,F,78
1061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,M,61
1062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,M,75
1063,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,M,60
1064,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3,F,81

In [54]:
df.query("`New MI 0/1` == 1").describe()

,DATA INTERVENTO,SMOKING (0: NO; 1: EX-SMOKER; 2: SMOKER),POOR MOBILITY 0/1 (severe impairment of mobility secondary to musculoskeletal or neurological dysfunction),DIABETES MELLITUS 0/1,INSULINE 0/1,ANGINE AT REST 0/1,ATRIAL FIBRILLATION 0/1,COPD 0/1,ACTIVE ENDOCARDITIS 0/1,PULMUNARY HYPERTENSION 0/1,...,DAY 5 sCreat mg/dl,DAY 5 eGFR,DAY 6 sCreat mg/dl,DAY 6 eGFR,7 days eGFR,Discharge (after 7 d) sCreat mg/dl,Discharge day,AKI 1/2/3(non_corretto),ESORDIO,FU
count,4.000000,4.00000,4.00,4.0,4.0,4.00000,4.00,4.0,4.0,4.0,...,3.000000,0.0,1.00,0.0,0.0,0.0,0.0,4.000000,0.0,0.0
mean,43203.250000,0.50000,0.25,0.0,0.0,0.50000,0.25,0.0,0.0,0.0,...,1.726667,NaN,2.02,NaN,NaN,NaN,NaN,1.250000,NaN,NaN
std,244.816087,0.57735,0.50,0.0,0.0,0.57735,0.50,0.0,0.0,0.0,...,0.790274,NaN,NaN,NaN,NaN,NaN,NaN,0.957427,NaN,NaN
min,42877.000000,0.00000,0.00,0.0,0.0,0.00000,0.00,0.0,0.0,0.0,...,1.020000,NaN,2.02,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,43087.750000,0.00000,0.00,0.0,0.0,0.00000,0.00,0.0,0.0,0.0,...,1.300000,NaN,2.02,NaN,NaN,NaN,NaN,0.750000,NaN,NaN
50%,43256.500000,0.50000,0.00,0.0,0.0,0.50000,0.00,0.0,0.0,0.0,...,1.580000,NaN,2.02,NaN,NaN,NaN,NaN,1.500000,NaN,NaN
75%,43372.000000,1.00000,0.25,0.0,0.0,1.00000,0.25,0.0,0.0,0.0,...,2.080000,NaN,2.02,NaN,NaN,NaN,NaN,2.000000,NaN,NaN
max,43423.000000,1.00000,1.00,0.0,0.0,1.00000,1.00,0.0,0.0,0.0,...,2.580000,NaN,2.02,NaN,NaN,NaN,NaN,2.000000,NaN,NaN

In [37]:
df_1.

AttributeError: 'DataFrame' object has no attribute 'sortby'